### PR TITLE
Delete Vixen

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by int-e** [comment]
I would prefer to keep the code in lambdabot, and just remove it from the default configuration.

**Comment by peti** [comment]
@puffnfresh, what is the rationale for removing this command? (Please excuse me if this sounds like a dumb question, but I don't really know what this command does exactly.)

**Comment by puffnfresh** [comment]
@int-e do you know if this is used by anybody? I don't think we should keep random unused code around.

@peti I started up a chat with LambdaBot in it, someone tried the Vixen command and got a very sexual response. This is inappropriate for my chat. I read the Vixen state file (lambdabot/State/vixen) to see what it's meant to do, and it seems like it's exactly to give back sexual responses.

I don't think it has any reason to exist. I did a search to see if anybody has discussed it before and [this page](http://www.vex.net/~trebla/vixen.txt) is the closest I've found. One of the recommendations was to delete Vixen and Nixon because of the problem I had in [166](https://github.com/lambdabot/lambdabot/pull/166#issuecomment-358765641).

**Comment by peti** [comment]
This pretty much the same problem as with "nixon". Removing the code seems like a bad idea to me. Rather, users running lambdabot should *configure* their bot appropriately.

**Pull request closed without merging**
