### PR TITLE
Support GHC 9

### PR DESCRIPTION
**Pull request by ncfavier**
Depends on:

- [x] https://github.com/lambdabot/dice/pull/2 (https://github.com/ncfavier/dice/commit/80d6fd443cb17b21d91b725f994ece6e8274e0a0)
- [X] https://github.com/mokus0/misfortune/pull/5 (https://github.com/ncfavier/misfortune/commit/59fe811f30b3544b71d19276076021bba82d2498)

I've disabled both plugins for the time being.

Builds fine on GHC 9.0.2.

Diff best viewed with "hide whitespace" on.

### CODE REVIEW

**Comment by ncfavier** [comment]
Sent a patch via email to the `knob` maintainer

<details><summary>GHC 9 support for knob</summary>

```
Hi, here's a patch to make knob compile with GHC 9.

Changes:
- IO.seek should now return the new offset so I used modifyMVar instead
  of modifyMVar_
- mkFileHandle now requires a RawIO instance for Device. Since this was
  not the case before and I don't think we need to actually support raw
  IO, I used DeriveAnyClass. Feel free to add a real implementation.

Cheers

Signed-off-by: Naïm Favier [<n@monade.li>](mailto:n@monade.li)
---
 lib/Data/Knob.hs | 20 ++++++++++----------
 1 file changed, 10 insertions(+), 10 deletions(-)

diff --git a/lib/Data/Knob.hs b/lib/Data/Knob.hs
index fa87ad2..f01d0a7 100644
--- a/lib/Data/Knob.hs
+++ b/lib/Data/Knob.hs
@@ -1,4 +1,4 @@
-{-# LANGUAGE DeriveDataTypeable #-}
+{-# LANGUAGE DeriveDataTypeable, DeriveAnyClass #-}
 
 -- |
 -- Module: Data.Knob
@@ -58,7 +58,7 @@ import qualified System.IO as IO
 newtype Knob = Knob (MVar.MVar ByteString)
 
 data Device = Device IO.IOMode (MVar.MVar ByteString) (MVar.MVar Int)
-	deriving (Typeable)
+	deriving (Typeable, IO.RawIO)
 
 instance IO.IODevice Device where
 	ready _ _ _ = return True
@@ -68,21 +68,21 @@ instance IO.IODevice Device where
 	
 	seek (Device _ _ var) IO.AbsoluteSeek off = do
 		checkOffset off
-		MVar.modifyMVar_ var (\_ -> return (fromInteger off))
-	
+		MVar.modifyMVar var (\_ -> return (fromInteger off, off))
+
 	seek (Device _ _ var) IO.RelativeSeek off = do
-		MVar.modifyMVar_ var (\old_off -> do
+		MVar.modifyMVar var (\old_off -> do
 			let new_off = toInteger old_off + off
 			checkOffset new_off
-			return (fromInteger new_off))
-	
+			return (fromInteger new_off, new_off))
+
 	seek dev@(Device _ _ off_var) IO.SeekFromEnd off = do
-		MVar.modifyMVar_ off_var (\_ -> do
+		MVar.modifyMVar off_var (\_ -> do
 			size <- IO.getSize dev
 			let new_off = size + off
 			checkOffset new_off
-			return (fromInteger new_off))
-	
+			return (fromInteger new_off, new_off))
+
 	tell (Device _ _ var) = fmap toInteger (MVar.readMVar var)
 	getSize (Device _ var _) = do
 		bytes <- MVar.readMVar var
-- 
2.35.1
```
</details>

**Comment by ncfavier** [comment]
Switched from `mwc-random` to `random`, and reenabled dice and fortune so that we can use this PR as a patch in nixpkgs.

**Comment by ncfavier** [comment]
Merged into my fork and published [5.3.1](https://hackage.haskell.org/package/lambdabot-5.3.1).

**Comment by l29ah** [comment]
It would be nice if you adjusted the cabal file with the actual git upstream.

**Comment by ncfavier** [comment]
Done

**Comment by int-e** [comment]
Sorry, I really let this slip... motivation is hard to come by. I'll invite @ncffavier to be co-owner of this org if they want it.

**Comment by ncfavier** [comment]
Thanks, I'll sync the repositories and revert the upstream tomorrow.

**Comment by ncfavier** [comment]
Done

**Pull request closed without merging**
