### PR TITLE
generate github action using haskell-ci

### PR DESCRIPTION
**Pull request by int-e**
Travis has become untenable for open source projects, so let's try the obvious alternative.

### CODE REVIEW

**Comment by peti** [comment]
What exactly makes Travis-CI untenable?

**Comment by int-e** [comment]
This sums it up nicely: https://ropensci.org/technotes/2020/11/19/moving-away-travis/#a-change-of-management

**Comment by int-e** [comment]
To elaborate for lambdabot specifically:

* the current Travis CI integration has stopped working, as far as I can see
* this is partly because I never had control over it; as far as I know, it was set up by @mokus0. But I didn't even try to take any action to migrate the account when they announced that thel shutdown of the travis-ci.org service was announced.
* the new *trial* account model for OSS projects would give us 1000 minutes of CPU time per month (possibly more, but we'd be at Travis CI's mercy for that), which divided by 60-120 minutes (which is how long a single build takes at the moment) really isn't a whole lot

**Comment by int-e** [comment]
Anyway, this seems to be working (if the newer ghc versions don't turn up any unexpected trouble). The new badge is untested, of course...

For the moment I see no harm in keeping the Travis configuration around (maybe some forks benefit from it).

Any comments?

**Pull request merged**
