### PR TITLE
Add support for server auto-reconnection and channels auto-rejoin

### PR DESCRIPTION
**Pull request by abbradar**
This set of changes:

1. Adds infrastructure for "persistent servers" (i.e. servers which we try to reconnect on failure). "Persistence" can be one-time (reconnect once) or lasting (reconnect always). Reconnection would be tried indefinitely with a 10s wait between retries. it can be stopped with a new command "disconnect" (see below).
2. Uses it instead of `ircStayConnected` to stop offlinerc.
3. Uses `ircChannels` which we now also properly clean up to rejoin channels after reconnection.
4. Makes "irc-connect" more synchronous -- now it doesn't return until RPL_WELCOME is received, which allows one to use "join" right after "irc-connect" in startup scripts.

I've added two new commands to avoid changing existing ones:

* "irc-persist-connect" acts like "irc-connect" but flags server as persistent (arguably this can be the default behavior or an additional argument to "irc-connect" instead, but I've avoided changing syntax/semantics of existing commands as much as possible).
* "disconnect" acts as "quit" but expects server name as the first argument, allowing one to disconnect lambdabot off one server from the other (or from offlinerc).

Some commands now behave a little different:

* "reconnect" now actually works, using new infrastructure.
* "irc-connect" waits till RPL_WELCOME is received.
* "quit" doesn't stop offlinerc when issued from on an IRC -- this was a bug.
* "quit" (and "disconnect") also remove server from "persistent servers" list, so they can be used to stop reconnection attempts.

Rationale for these changes:

I'm keeping lambdabot on a home server; Internet connection can be unreliable sometimes, and I'd like to avoid manual steps required to restore the bot after a network failure. The synchronous irc-connect change is to avoid issuing join commands manually after starting a bot. As a whole this allows me to have a systemd service which starts lambdabot with a provided startup script; to start the bot and join all needed channels it's now enough to just start the service, and with automatic reconnection this doesn't require maintenance after network problems.

### CODE REVIEW

**Comment by int-e** [comment]
Thanks for working on this! I'll have a closer look at the patches later this week.

**Comment by abbradar** [comment]
I've redone commits to make this easier to review. Thanks in advance!

**Comment by int-e** [comment]
I've gone through the patches; they look reasonable, and should improve lambdabot's behavior (I have not actually tested the code yet).

 * I'd like the 10 second timeouts to be configurable, but I can do that myself. 
 * there's a comment about the retry loop at https://github.com/abbradar/lambdabot/commit/643c9958d9d78c13172c066c2b316c3d449ba0da

**Comment by abbradar** [comment]
I've made timeouts configurable, fixed the retry loop and also made sure the socket would be closed from our side.

**Pull request merged**
