### PR TITLE
Delete 'nixon' command

### PR DESCRIPTION
**Pull request by puffnfresh**
This is categorised under "offensive" in misfortune.

### CODE REVIEW

**Comment by peti** [comment]
I'm not sure whether I understand this correctly. What does it mean that this quote collection is categorized as "offensive"? Does `misfortune` still support it? I mean, Lambdabot does a couple of things that may be interpreted as offensive depending on how sensitive you are (`@slap`) and that by itself doesn't seem to be a reason to remove the feature. Am I missing something?

**Comment by puffnfresh** [comment]
My rationale is that I set up a chat with LambdaBot installed. I had the default settings. Vixen is included by default and someone tried it out. Vixen said some sexual things, unnecessary and inappropriate for my chat. I removed Vixen but the command got autocorrected to Nixon, which meant my chat started containing racist things. Went from bad to worse. [Turns out this EXACT thing has happened before](http://www.vex.net/~trebla/vixen.txt).

You can take a look at the quotes in the repo:

https://github.com/mokus0/misfortune/blob/master/data/offensive/lambdabot/nixon

Towards the bottom you'll find some homophobic and racist things. It's extremely different to the slap command, which doesn't discriminate.

The problem was made worse because of the autocorrection and I didn't recognise the first few quotes. I was totally confused why LambdaBot said some racist things. No indication from LambdaBot that it was quoting Nixon.

Does anybody actually want these random Nixon quotes in their chat?

**Comment by peti** [comment]
OK, I've thought about this complaint for a while, and I see your point. Personally, I don't want these quotes either.

To be fair, though, what the difference between humor and being offensive is often small and very subjective, and outright removing these features from the code seems inappropriate. Rather, I believe that people running lambdabot should *configure* their bot appropriately. That is what I do, for example, I remove the fortune stuff completely because I fell it's a stupid feature. I wouldn't want to impose that personal opinion on everyone else, though.

**Comment by puffnfresh** [comment]
@peti I configured LambdaBot because I had to. I think deleting things which aren't used by anybody is probably a useful thing to do, so that we don't have to configure things.

Seems like no cost to me.

**Comment by peti** [comment]
> I think deleting things which aren't used by anybody is probably a useful thing to do.

As far as I can tell, you cannot possibly know whether anybody uses those modules or not.

**Pull request closed without merging**
